<?php
/**
 * @file
 * Code for the Users feature.
 */

include_once 'hr_users.features.inc';

/** 
 * Implementation of hook_entity_info_alter()
 */
function hr_users_entity_info_alter(&$entity_info) {

  // Quick links
  $entity_info['fieldable_panels_pane']['bundles']['hr_users'] = array(
    'label' => t('Users'),
    'pane category' => t('Users'),
    'pane top level' => TRUE,
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/hr-users',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_og_features_registry()
 */
function hr_users_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'hr_users';
  $feature->name = t('People');
  $feature->description = t('Show members of your space.');
  $feature->components = array(
    'pane' => array(
      'hr_users-space_members',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

/**
 * Implements hook_og_features_toggle($entity, $entity_id, $entity_type, $features)
 */
function hr_users_og_features_toggle($entity, $entity_id, $entity_type, $features) {
  if (isset($features['hr_users'])) {
    $mlid = og_menu_single_get_link_mlid('node', $entity_id);
    if (empty($features['hr_users'])) {
      menu_link_delete(NULL, 'node/'.$entity_id.'/people');
    }
    else {
      // See if menu link already exists
      $menu_link = menu_link_get_preferred('node/'.$entity_id.'/people', OG_MENU_SINGLE_MENU_NAME);
      if (empty($menu_link)) {
        $menu_link = array(
          'link_path' => 'node/'.$entity_id.'/people',
          'link_title' => 'People',
          'menu_name' => OG_MENU_SINGLE_MENU_NAME,
          'weight' => 6,
          'plid' => $mlid,
        );
        menu_link_save($menu_link);
      }
    }
  }

}

